version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8
  
jobs:
  functions-check:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-deps-{{ checksum "package-lock.json" }}
            - v4-deps-{{ checksum "functions/package-lock.json" }}
      - run: npm install
      - run: cd functions && npm install
      - save_cache:
          paths:
            - node_modules
          key: v4-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - functions/node_modules
          key: v4-deps-{{ checksum "functions/package-lock.json" }}
      - run: cd functions && npm run test

  firebase-deploy:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-deps-{{ checksum "package-lock.json" }}
            - v4-deps-{{ checksum "functions/package-lock.json" }}
      - run: npm install
      - run: cd functions && npm install
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-and-maybe-deploy:
    jobs:
      - functions-check

      - firebase-deploy:
          requires:
            - functions-check
          filters:
            branches:
              only: master