version: 2
defaults: &defaults
  docker:
    - image: circleci/node:10
jobs:
  functions-check:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "functions/package-lock.json" }}
      - run: cd functions && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-dependencies-{{ checksum "functions/package-lock.json" }}
      - run: cd functions && npm run test

  firebase-deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "functions/package-lock.json" }}
      - run: npx firebase deploy --token "$FIREBASE_TOKEN" --only functions

workflows:
  version: 2
  build-and-maybe-deploy:
    jobs:
      - functions-check

      - firebase-deploy:
          requires:
            - functions-check
          filters:
            branches:
              only: master