version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8
  
jobs:
  functions-check:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - save_cache:
          key: v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - /root/.npm
      - run: npm ci
      - run: cd functions && npm ci
      - save_cache:
          key: v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - /root/.npm
      - run: cd functions && npm run test

  firebase-deploy:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run: npm ci
      - run: cd functions && npm ci
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only functions

workflows:
  version: 2
  build-and-maybe-deploy:
    jobs:
      - functions-check

      - firebase-deploy:
          requires:
            - functions-check
          filters:
            branches:
              only: master