version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8
  
jobs:
  check-all:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run: 
          name: Install dependencies (Web Client)
          command: npm ci
      - run: 
          name: Install dependencies (Cloud Functions)
          command: cd functions && npm ci
      - save_cache:
          key: v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - /root/.npm
      - run: 
          name: Build (Web Client)
          command: npm run build
      - run: 
          name: Running test suite (functions)
          command: cd functions && npm run test

  firebase-deploy:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run: 
          name: Install web client dependencies
          command: npm ci
      - run: 
          name: Install cloud function dependencies
          command: cd functions && npm ci
      - run: 
          name: Deploy to Firebase
          command: npx firebase deploy -P production --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-and-maybe-deploy:
    jobs:
      - check-all

      - firebase-deploy:
          requires:
            - check-all
          filters:
            branches:
              only: master