version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8
  
jobs:
  functions-check:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run: 
          name: Install dependencies (Web Client)
          command: npm ci
      - run: 
          name: Install dependencies (Cloud Functions)
          command: cd functions && npm ci
      - save_cache:
          key: v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - /root/.npm
      - run: 
          name: Running test suite
          command: cd functions && npm run test

  firebase-deploy:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-web-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run: 
          name: Install web client dependencies
          command: npm ci
      - run: 
          name: Install cloud function dependencies
          command: cd functions && npm ci
      - run: 
          name: Deploy to Firebase
          command: npx firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-and-maybe-deploy:
    jobs:
      - functions-check

      - firebase-deploy:
          requires:
            - functions-check
          filters:
            branches:
              only: master